---
title: "R Day 2"
author: "Nora Xu"
date: "9/18/2018"
output: html_document
---

```{r}
here::here("data", "gapminder5.csv")
gapminder <- read.csv(here::here("data", "gapminder5.csv"), stringsAsFactors = F)
str(gapminder)
```

##Convert factor to character 
```{r}
gapminder <- read.csv(here::here("data", "gapminder5.csv"))
gapminder$country <- as.character(gapminder$country)
gapminder$continent <- as.character(gapminder$continent)
str(gapminder)
```

##Loop
```{r}
for (i in 1:nrow(gapminder)) {
  gapminder$gdp[i] <- gapminder$pop[i] * gapminder$gdpPercap[i]
}

log_gapPercap <- log(gapminder$gdpPercap)
log_pop <- log(gapminder$pop)

for (i in unique(gapminder$continent)) {
  mean_life <- mean(gapminder$lifeExp[gapminder$continent == i])
  print(paste(i, ": ", mean_life))
}


```


```{r}
year = 1987
while (year <= 2002) {
  deviation <- sd(gapminder$lifeExp[gapminder$year == year], na.rm = F)
  print(paste(year, ":", deviation))
  year = year+5
}
```

```{r}

for (year in unique(gapminder$year)) {
  mean_pop <- mean(gapminder$pop[gapminder$year == year], na.rm = T)
  if (year < 1987){
    print("Sorry the year is less than 1987")
  }else{
    print(paste("The mean populatio for year", year, "is", mean_pop))
  }
}
```


```{r}
sum = function(continent){
  minn = min(gapminder$lifeExp[gapminder$continent == continent], na.rm = T)
  maxx = max(gapminder$lifeExp[gapminder$continent == continent], na.rm = T)
  meann = mean(gapminder$lifeExp[gapminder$continent == continent], na.rm = T)
  mediann = median(gapminder$lifeExp[gapminder$continent == continent], na.rm = T)
  print(paste("The mean, median, min and max for life expectancy for continent", continent, "are respectively", meann, ",", mediann, ",", minn, "and", maxx))
}

sum("Asia")
```

